services:
  postgres:
    image: postgres:16
    container_name: flowcore-db
    environment:
      POSTGRES_USER: flowcore
      POSTGRES_PASSWORD: flowcore123
      POSTGRES_DB: FlowCoreDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: