services:
  postgres:
    image: postgres:16
    container_name: flowcore-db
    environment:
      POSTGRES_USER: flowcore
      POSTGRES_PASSWORD: flowcore123
      POSTGRES_DB: FlowCoreDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowcore-api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=FlowCoreDb;Username=flowcore;Password=flowcore123"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: